# Generated by Django 5.2.12 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'order_assigned'", max_length=100, unique=True
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="e.g. 'Partner Assigned!'", max_length=200
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="e.g. '{partner_name} has been assigned to your order {order_id}'"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("PARTNER", "Partner"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "recipient_id",
                    models.IntegerField(help_text="Customer or Partner profile ID"),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ORDER_UPDATE", "Order Update"),
                            ("INVOICE", "Invoice"),
                            ("WALLET", "Wallet"),
                            ("SYSTEM", "System"),
                            ("BROADCAST", "Broadcast"),
                        ],
                        default="ORDER_UPDATE",
                        max_length=15,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. order_id for deep-linking",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "city_id",
                    models.IntegerField(
                        blank=True,
                        help_text="For city-scoped broadcast filtering",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_type", "recipient_id", "is_read"],
                        name="notificatio_recipie_cbf482_idx",
                    )
                ],
            },
        ),
    ]
