# Generated by Django 5.2.12 on 2026-03-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of customer rate at collection time",
                        max_digits=10,
                    ),
                ),
                (
                    "partner_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of partner rate at collection time",
                        max_digits=10,
                    ),
                ),
                (
                    "customer_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="weight_kg * customer_rate",
                        max_digits=12,
                    ),
                ),
                (
                    "partner_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="weight_kg * partner_rate",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        db_index=True,
                        help_text="City-prefixed ID, e.g. KM-BEL-2024-48291",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ASSIGNED", "Assigned"),
                            ("ON_THE_WAY", "On The Way"),
                            ("ARRIVED", "Arrived"),
                            ("COLLECTING", "Collecting"),
                            ("AWAITING_INVOICE", "Awaiting Invoice"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("pickup_date", models.DateField()),
                (
                    "pickup_slot",
                    models.CharField(help_text="e.g. '10:00-11:00'", max_length=20),
                ),
                (
                    "pickup_slot_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Parsed datetime of slot start — for TAT#2",
                        null=True,
                    ),
                ),
                (
                    "scrap_photos",
                    models.JSONField(
                        blank=True, default=list, help_text="List of Cloudinary URLs"
                    ),
                ),
                ("scrap_description", models.TextField(blank=True, null=True)),
                (
                    "arrival_otp",
                    models.CharField(
                        blank=True,
                        help_text="6-digit code set when partner assigned",
                        max_length=6,
                    ),
                ),
                ("arrival_otp_verified", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.CharField(
                        blank=True,
                        choices=[("CUSTOMER", "Customer"), ("ADMIN", "Admin")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("on_the_way_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("scrap_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("invoice_approved_at", models.DateTimeField(blank=True, null=True)),
                ("payment_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="cities.city",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="accounts.partnerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(help_text="1-5 stars")),
                ("feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
