# Generated by Django 5.2.12 on 2026-03-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scrap_items",
                to="pricing.scrapcategory",
            ),
        ),
        migrations.AddField(
            model_name="scrapitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrap_items",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["city", "status"], name="orders_orde_city_id_126c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["partner", "status"], name="orders_orde_partner_6365f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "status"], name="orders_orde_custome_c9b64a_idx"
            ),
        ),
    ]
