# Generated by Django 5.2.12 on 2026-03-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="City display name, e.g. 'Belgaum'", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier, e.g. 'belgaum'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="State name, e.g. 'Karnataka'", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Admin can disable a city to hide it from dropdowns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["name"],
            },
        ),
    ]
