# Generated by Django 5.2.12 on 2026-03-10 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("B2C", "Individual (B2C)"),
                            ("B2B", "Business (B2B)"),
                        ],
                        default="B2C",
                        max_length=5,
                    ),
                ),
                (
                    "expo_push_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="cities.city",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                (
                    "otp_hash",
                    models.CharField(
                        help_text="bcrypt hash of the OTP", max_length=128
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("ARRIVAL_VERIFY", "Arrival Verification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Max 3 attempts before lockout"
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="created_at + 5 minutes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "purpose", "created_at"],
                        name="accounts_ot_phone_n_601862_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "aadhaar_doc_url",
                    models.CharField(
                        blank=True,
                        help_text="Cloudinary URL for Aadhaar document",
                        max_length=500,
                    ),
                ),
                (
                    "vehicle_doc_url",
                    models.CharField(
                        blank=True,
                        help_text="Cloudinary URL for vehicle registration",
                        max_length=500,
                    ),
                ),
                (
                    "license_doc_url",
                    models.CharField(
                        blank=True,
                        help_text="Cloudinary URL for driving license",
                        max_length=500,
                    ),
                ),
                ("godown_address", models.TextField(blank=True, null=True)),
                (
                    "godown_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "godown_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                (
                    "expo_push_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partners",
                        to="cities.city",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
